name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env.local for Vite
        run: |
          cat > .env.local << 'EOF'
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=zent-9e08f.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID=zent-9e08f
          VITE_FIREBASE_STORAGE_BUCKET=zent-9e08f.appspot.com
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          EOF

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools deploy --project zent-9e08f --token ${{ secrets.FIREBASE_TOKEN }}
